#!/usr/bin/env python

# pylint: disable=C0111

import argparse
import getpass
import glob
import mechanize
import mimetypes
import os
import os.path
import re
import shutil

LOGIN_URL     = 'https://www.codeeval.com/accounts/login/'
DASHBOARD_URL = 'https://www.codeeval.com/dashboard/'
SUBMIT_URL    = 'https://www.codeeval.com/open_challenges/{challenge_id}/submit'

BROWSER = mechanize.Browser()
BROWSER.set_handle_robots(False)
BROWSER.set_handle_refresh(False)

COOKIE_JAR_FILE = 'cookies.txt'

COOKIE_JAR = mechanize.LWPCookieJar()
if os.path.exists(COOKIE_JAR_FILE):
    COOKIE_JAR.load(COOKIE_JAR_FILE)
BROWSER.set_cookiejar(COOKIE_JAR)

mimetypes.add_type('text/java', '.java')

def get_browser(url):
    BROWSER.open(url)

    if BROWSER.geturl() != url:
        res = login()

        if res.geturl() != DASHBOARD_URL:
            print 'Unable to login'
            exit(1)

        BROWSER.open(url)

    return BROWSER

def login():
    username = raw_input('Username: ')
    password = getpass.getpass()

    browser = get_browser(LOGIN_URL)

    login_form = browser.form = list(browser.forms())[-1]
    login_form.find_control('username').value = username
    login_form.find_control('password').value = password

    return browser.submit()

def create_challenge(args):
    challenge_name = args.challenge_name.lower().replace(' ', '_')
    filename_root  = '{0}_{1}'.format(args.challenge_id, challenge_name)

    for lang in os.listdir('.'):
        if not os.path.isdir(lang) or lang.startswith('.'):
            continue

        template_match = glob.glob(os.path.join(lang, 'template.*'))
        if len(template_match) == 0:
            continue

        template = template_match[0]
        filename = os.path.join(lang, filename_root) + os.path.splitext(template)[1]

        if os.path.exists(filename):
            print 'Skipping {0}...'.format(filename)
        else:
            print 'Creating {0}...'.format(filename)

            shutil.copyfile(template, filename)

def submit_challenge(args):
    for solution in args.files:
        print 'Submitting {0}...'.format(solution)

        extension   = os.path.splitext(solution)[1]
        mimetype    = mimetypes.types_map[extension]
        file_handle = None
        try:
            file_handle = open(solution)
        except:
            print 'Unable to read solution file'
            exit(1)

        challenge_id = re.search(r'\d+', solution).group(0)[0]
        url          = SUBMIT_URL.format(challenge_id = challenge_id)

        browser = get_browser(url)

        form = browser.form = list(browser.forms())[0]
        file_control = form.find_control(name = 'submission')
        file_control.add_file(
            file_handle,
            filename = solution,
            content_type = mimetype
        )

        browser.submit()

def list_challenges(args):
    pass

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = 'Create solution files for each language for a challenge')
    subparsers = parser.add_subparsers()

    create_parser = subparsers.add_parser('create')
    create_parser.add_argument('challenge_id', type = int,
                        help = 'Challenge ID')
    create_parser.add_argument('challenge_name', type = str,
                        help = 'Challenge name')
    create_parser.set_defaults(func = create_challenge)

    submit_parser = subparsers.add_parser('submit')
    submit_parser.add_argument('files', type = str,
                        nargs = '+',
                        help = 'Solution file')
    submit_parser.set_defaults(func = submit_challenge)

    list_parser = subparsers.add_parser('list')
    group = list_parser.add_mutually_exclusive_group(required = True)
    group.add_argument('--all', action = 'store_true',
                    help = 'List all challenges')
    group.add_argument('--completed', action = 'store_true',
                    help = 'List all completed challenges')
    group.add_argument('--open', action = 'store_true',
                    help = 'List all incomplete challenges')

    list_parser.add_argument('--difficulty', type = str,
                    required = False,
                    choices = ['easy', 'medium', 'hard'],
                    help = 'Filter based on difficutly')
    list_parser.add_argument('--order', type = str,
                    required = False,
                    choices = ['asc', 'desc'],
                    help = 'Order challenges by challenge ID')
    list_parser.set_defaults(func = list_challenges)

    args = parser.parse_args()
    args.func(args)

    COOKIE_JAR.save(COOKIE_JAR_FILE)

