#!/usr/bin/env python

# pylint: disable=C0111

import argparse
import getpass
import glob
import mechanize
import os
import os.path
import re
import shutil

LOGIN_URL     = 'https://www.codeeval.com/accounts/login/'
DASHBOARD_URL = 'https://www.codeeval.com/dashboard/'
SUBMIT_URL    = 'https://www.codeeval.com/open_challenges/{challenge_id}/submit'

BROWSER = mechanize.Browser()
BROWSER.set_handle_robots(False)
BROWSER.set_handle_refresh(False)

COOKIE_JAR_FILE = 'cookies.txt'

COOKIE_JAR = mechanize.LWPCookieJar()
COOKIE_JAR.load(COOKIE_JAR_FILE)
BROWSER.set_cookiejar(COOKIE_JAR)

def get_browser():
    return BROWSER

def is_logged_in(res = None):
    if res == None:
        browser = get_browser()
        browser.open(DASHBOARD_URL)
        res = browser

    return res.geturl() == DASHBOARD_URL

def login():
    username = raw_input('Username: ')
    password = getpass.getpass()

    browser = get_browser()
    browser.open(LOGIN_URL)

    login_form = browser.form = list(browser.forms())[-1]
    login_form.find_control('username').value = username
    login_form.find_control('password').value = password

    return browser.submit()

def login_required(func):
    def wrapper(args):
        if not is_logged_in():
            res = login()

            if not is_logged_in(res):
                print 'Unable to login'
                exit(1)

        return func(args)

    return wrapper

def create_challenge(args):
    challenge_name = args.challenge_name.lower().replace(' ', '_')
    filename_root  = '{0}_{1}'.format(args.challenge_id, challenge_name)

    for lang in os.listdir('.'):
        if not os.path.isdir(lang) or lang.startswith('.'):
            continue

        template_match = glob.glob(os.path.join(lang, 'template.*'))
        if len(template_match) == 0:
            continue

        template = template_match[0]
        filename = os.path.join(lang, filename_root) + os.path.splitext(template)[1]

        if os.path.exists(filename):
            print 'Skipping {0}...'.format(filename)
        else:
            print 'Creating {0}...'.format(filename)

            shutil.copyfile(template, filename)

@login_required
def submit_challenge(args):
    solution = args.file
    contents = None
    try:
        file_handle = open(solution)
        contents    = file_handle.read()
    except:
        print 'Unable to read solution file'
        exit(1)

    challenge_id = re.search(r'\d+', solution).group(0)[0]
    url          = SUBMIT_URL.format(challenge_id = challenge_id)

    browser = get_browser()
    browser.open(url)

    for f in browser.forms():
        print f

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = 'Create solution files for each language for a challenge')
    subparsers = parser.add_subparsers()

    create_parser = subparsers.add_parser('create')
    create_parser.add_argument('challenge_id', type = int,
                        help = 'Challenge ID')
    create_parser.add_argument('challenge_name', type = str,
                        help = 'Challenge name')
    create_parser.set_defaults(func = create_challenge)

    submit_parser = subparsers.add_parser('submit')
    submit_parser.add_argument('file', type = str,
                        help = 'Solution file')
    submit_parser.set_defaults(func = submit_challenge)

    args = parser.parse_args()
    args.func(args)

    COOKIE_JAR.save(COOKIE_JAR_FILE)

